### ISSUE TITLE
Questions about AlignAndPostProcessTransform.

### ISSUE THREAD

**Issue by Logan-Kang** [allenday/dataflow-genomics#32]
> AlignAndPostProcessTransform - contains queue of genomics transformation namely Sequence alignment (FASTQ->SAM), converting to binary format (SAM->BAM), sorting FASTQ and merging FASTQ in scope of single sample

 Is fastq the only extension used in this process? Can't I use fq files or other extensions?

**Comment by pseveryn** [comment]
@Logan-Kang, actually, `.fq`  is a shortened variant of `.fastq`. Both formats are supported. 
All that you need is to provide custom UriProvider implementation like this: https://github.com/allenday/dataflow-genomics/blob/6e3cdd1999c6120ea35c81b803be85f55b7af7b0/genomics-dataflow-core/src/main/java/com/google/allenday/genomics/core/io/DefaultUriProvider.java

**Comment by pseveryn** [comment]
@Logan-Kang added possibility to set `.fq` extension as DefaultUriProvider argument
https://github.com/allenday/dataflow-genomics/pull/33

**Comment by Logan-Kang** [comment]
also plz check readme last line...
In the readme file of giab-example, "with" in the last line of the java command of [Running pipeline] seems to be missing.

============
java -cp target/giab-example-1.0.0.jar \
    com.google.allenday.genomics.core.example.GiabExampleApp \
        --project=$PROJECT_ID \
        --runner=DataflowRunner \
        --region=$REGION \
        --inputCsvUri=$CSV_URI \
        --workerMachineType=$MACHINE_TYPE \
        --maxNumWorkers=$MAX_WORKERS \
        --numWorkers=$MAX_WORKERS \
        --diskSizeGb=$DISK_SIZE \
        --stagingLocation=$STAGING_LOC \
        --tempLocation=$TEMP_LOC \
        --srcBucket=$SRC_BUCKET_NAME \
        --refDataJsonString=$REFERENCE_DATA_JSON_STRING \
        --outputGcsUri=$OUTPUT_GCS_URI \
        --controlPipelineWorkerRegion=$CONTROL_PIPELIE_WORKER_REGION \
        --stepsWorkerRegion=$STEPS_WORKER_REGION \
        --makeExamplesCoresPerWorker=$M_E_CORES \
        --makeExamplesRamPerWorker=$M_E_MEMORY \
        --makeExamplesDiskPerWorker=$M_E_DISK \
        --callVariantsCoresPerWorker=$C_V_CORES \
        --callVariantsRamPerWorker=$C_V_MEMORY \
        --callVariantsDiskPerWorker=$C_V_DISK \
        --postprocessVariantsCores=$P_V_CORES \
        --postprocessVariantsRam=$P_V_MEMORY \
        --postprocessVariantsDisk=$P_V_DISK \
        --makeExamplesWorkers=$M_E_WORKERS \
        --callVariantsWorkers=$C_V_WORKERS \
        --deepVariantShards=$M_E_SHARDS \
        **--exportVcfToBq=True \**
        --vcfBqDatasetAndTablePattern=$VCF_BQ_TABLE_PATH_PATTERN

=============
we change that bold line and test it :         --withExportVcfToBq=False

**Comment by pseveryn** [comment]
@Logan-Kang , yes, you are right. Thanks! Actually, this is a redundant parameter, because it is `True` by default.
Removed in: https://github.com/allenday/dataflow-genomics/pull/34

**Comment by Logan-Kang** [comment]
Hi.

For the reason that fq was configured to work, I did a mvn clean package command after a new git clone.
mvn build success, but an error occurred while running the actual java cp command.

==============================
heolgon_kang@cloudshell:~/200318_gcgpoc/dataflow-genomics/giab-example (gcgpoc)$ java -cp target/giab-example-1.0.0.jar \
>     com.google.allenday.genomics.core.example.GiabExampleApp \
>         --project=$PROJECT_ID \
>         --runner=DataflowRunner \
>         --region=$REGION \
>         --inputCsvUri=$CSV_URI \
>         --workerMachineType=$MACHINE_TYPE \
>         --maxNumWorkers=$MAX_WORKERS \
>         --numWorkers=$MAX_WORKERS \
>         --diskSizeGb=$DISK_SIZE \
>         --stagingLocation=$STAGING_LOC \
>         --tempLocation=$TEMP_LOC \
>         --srcBucket=$SRC_BUCKET_NAME \
>         --refDataJsonString=$REFERENCE_DATA_JSON_STRING \
>         --outputGcsUri=$OUTPUT_GCS_URI \
>         --controlPipelineWorkerRegion=$CONTROL_PIPELIE_WORKER_REGION \
>         --stepsWorkerRegion=$STEPS_WORKER_REGION \
>         --makeExamplesCoresPerWorker=$M_E_CORES \
>         --makeExamplesRamPerWorker=$M_E_MEMORY \
>         --makeExamplesDiskPerWorker=$M_E_DISK \
>         --callVariantsCoresPerWorker=$C_V_CORES \
>         --callVariantsRamPerWorker=$C_V_MEMORY \
>         --callVariantsDiskPerWorker=$C_V_DISK \
>         --postprocessVariantsCores=$P_V_CORES \
>         --postprocessVariantsRam=$P_V_MEMORY \
>         --postprocessVariantsDisk=$P_V_DISK \
>         --makeExamplesWorkers=$M_E_WORKERS \
>         --callVariantsWorkers=$C_V_WORKERS \
>         --deepVariantShards=$M_E_SHARDS \
>         --withExportVcfToBq=False
[main] INFO org.apache.beam.runners.dataflow.DataflowRunner - PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 1 files. Enable logging at DEBUG level to see which files will be staged.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error in custom provider, java.lang.NullPointerException
  at com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignService(BatchProcessingModule.java:89)
  while locating com.google.allenday.genomics.core.processing.align.AlignService
    for the 1st parameter of com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignFn(BatchProcessingModule.java:142)
  at com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignFn(BatchProcessingModule.java:142)
  while locating com.google.allenday.genomics.core.processing.align.AlignFn
    for the 1st parameter of com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignTransform(BatchProcessingModule.java:178)
  at com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignTransform(BatchProcessingModule.java:178)
  while locating com.google.allenday.genomics.core.processing.align.AlignTransform
    for the 1st parameter of com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignAndPostProcessTransform(BatchProcessingModule.java:195)
  at com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignAndPostProcessTransform(BatchProcessingModule.java:195)
  while locating com.google.allenday.genomics.core.processing.AlignAndPostProcessTransform

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at com.google.allenday.genomics.core.example.GiabExampleApp.main(GiabExampleApp.java:40)
Caused by: java.lang.NullPointerException
        at com.google.allenday.genomics.core.batch.BatchProcessingModule.provideAlignService(BatchProcessingModule.java:89)
        at com.google.allenday.genomics.core.batch.BatchProcessingModule$$FastClassByGuice$$b0c8ba05.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        ... 2 more
====

plz check

thank you

**Comment by pseveryn** [comment]
Thanks! I've taken this into work

**Comment by pseveryn** [comment]
Fixed in https://github.com/allenday/dataflow-genomics/pull/35

**Comment by Logan-Kang** [comment]
Hi

Today allen merged # 35. So I tested it now, but I still can't read the fq file, and the error message is [404 Not Found No such object: * .fastq].
I'll attach the error content. The original file name is TNBC143_M_1.fq.

2020-04-06 10:17:47.434 JSTError message from worker: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: com.google.cloud.storage.StorageException: 404 Not Found No such object: gcgpoc-src-jp/fastq/GIAB-MGISEQ/NA12878/TNBC143_M_1.fastq org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:184) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:107) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:126) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:54) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:120) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159) org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:305) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107) java.util.concurrent.FutureTask.run(FutureTask.java:266) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) java.lang.Thread.run(Thread.java:748) Caused by: org.apache.beam.sdk.util.UserCodeException: com.google.cloud.storage.StorageException: 404 Not Found No such object: gcgpoc-src-jp/fastq/GIAB-MGISEQ/NA12878/TNBC143_M_1.fastq org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:34) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:222) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:182) ... 21 more Caused by: com.google.cloud.storage.StorageException: 404 Not Found No such object: gcgpoc-src-jp/fastq/GIAB-MGISEQ/NA12878/TNBC143_M_1.fastq com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220) com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:644) com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127) com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124) com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) com.google.cloud.RetryHelper.run(RetryHelper.java:74) com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124) com.google.allenday.genomics.core.io.FastqReader.readFastqBlobWithReadCountLimit(FastqReader.java:115) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn.lambda$processElement$1(SplitFastqIntoBatches.java:169) java.util.Optional.ifPresent(Optional.java:159) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn.processElement(SplitFastqIntoBatches.java:143) Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found No such object: gcgpoc-src-jp/fastq/GIAB-MGISEQ/NA12878/TNBC143_M_1.fastq com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150) com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417) com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1132) com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515) com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448) com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:476) com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:6281) com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:622) com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127) com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124) com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) com.google.cloud.RetryHelper.run(RetryHelper.java:74) com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:124) com.google.allenday.genomics.core.io.FastqReader.readFastqBlobWithReadCountLimit(FastqReader.java:115) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn.lambda$processElement$1(SplitFastqIntoBatches.java:169) java.util.Optional.ifPresent(Optional.java:159) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn.processElement(SplitFastqIntoBatches.java:143) com.google.allenday.genomics.core.processing.SplitFastqIntoBatches$ReadFastqPartFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:222) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:182) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:107) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:126) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:54) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:120) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:114) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159) org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:305) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107) java.util.concurrent.FutureTask.run(FutureTask.java:266) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) java.lang.Thread.run(Thread.java:748)

**Comment by Logan-Kang** [comment]
Is there any difference in java cp command to test with fq file?

**Comment by pseveryn** [comment]
Yes. To use `.fq` files you should specify this format here:
https://github.com/allenday/dataflow-genomics/blob/fac579acfcae0c50ffc557babcdfa3df49536461/giab-example/src/main/java/com/google/allenday/genomics/core/example/GiabExampleAppModule.java#L64
like this:
`return DefaultUriProvider.withDefaultProviderRule(srcBucket, FastqExt.FQ);`

**Comment by pseveryn** [comment]
Created issue. Will add this functionality today
https://github.com/allenday/dataflow-genomics/issues/36

**Comment by pseveryn** [comment]
https://github.com/allenday/dataflow-genomics/pull/37
here was added possibility to set `.fq` input format from the program arguments. Just add:
`   --fastqExt=FQ` to java -cp command

**Comment by Logan-Kang** [comment]
hello @Pseverin 
I downloaded it today and tested it after maven update, but fastqExt still doesn't set options.

Exception in thread "main" java.lang.IllegalArgumentException: Class interface com.google.allenday.genomics.core.batch.BatchProcessingPipelineOptions missing a property named 'fastqExt'.
        at org.apache.beam.sdk.options.PipelineOptionsFactory.parseObjects(PipelineOptionsFactory.java:1625)
        at org.apache.beam.sdk.options.PipelineOptionsFactory.access$400(PipelineOptionsFactory.java:115)
        at org.apache.beam.sdk.options.PipelineOptionsFactory$Builder.as(PipelineOptionsFactory.java:298)
        at com.google.allenday.genomics.core.example.GiabExampleApp.main(GiabExampleApp.java:25)

**Comment by Logan-Kang** [comment]
An error occurs even if you proceed except the fastqExt option.
-----
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
        at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:224)
        at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:155)
        at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
        at org.apache.beam.sdk.Pipeline.create(Pipeline.java:149)
        at com.google.allenday.genomics.core.example.GiabExampleApp.main(GiabExampleApp.java:33)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:214)
        ... 4 more
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.expireAfterWrite(Ljava/time/Duration;)Lcom/google/common/cache/CacheBuilder;
        at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:149)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:243)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:82)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:104)
        at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:87)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
        at com.sun.proxy.$Proxy22.getGcsUtil(Unknown Source)
        at org.apache.beam.sdk.extensions.gcp.storage.GcsPathValidator.verifyPathIsAccessible(GcsPathValidator.java:83)
        at org.apache.beam.sdk.extensions.gcp.storage.GcsPathValidator.validateOutputFilePrefixSupported(GcsPathValidator.java:53)
        at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:308)
        at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:288)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
        at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
        at com.sun.proxy.$Proxy0.getGcpTempLocation(Unknown Source)
        at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:249)
        ... 9 more
-----

After looking up a bit, it is called a Java version problem. Need openjdk update?

test instance's java version is :
kcgadmin@kcg-gcgtest:~/dataflow-genomics/giab-example$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
kcgadmin@kcg-gcgtest:~/dataflow-genomics/giab-example$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-12-amd64", arch: "amd64", family: "unix"

**Comment by pseveryn** [comment]
@Logan-Kang I will look at this

**Comment by pseveryn** [comment]
There were 2 reasons for the problem:
1. In new lib versions, we add automatic detection of FASTQ extension. That's why now there is **no need** in --fastqExt=FQ. Added support of old version's options  in https://github.com/allenday/dataflow-genomics/pull/42
2. There was a dependency conflict because of update the Apache Beam version. Fixed in https://github.com/allenday/dataflow-genomics/pull/42

@allenday, please check and merge https://github.com/allenday/dataflow-genomics/pull/42

**Comment by Logan-Kang** [comment]
Thank you!
